version: '3.7'
services:
   db:
        image: postgres:15
        container_name: index_db
        restart: always
        environment:
                - POSTGRES_USER=odoo
                - POSTGRES_PASSWORD=hqd8^QDgh#WW
                - POSTGRES_DB=postgres
                - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
                - "51514:5432"
        volumes:
                - db-data:/var/lib/postgresql/data/pgdata
        networks:
                - tritel_index
   odoo:        
        image: dennokorir/tritel-index:15.0
        container_name: index_odoo
        restart: always
        ports:
                - "8015:8069"
                - "8014:8072"
        links:
                - db:db
        depends_on:
                - db
        volumes:
                - ./config:/etc/odoo
                - ./custom-addons:/mnt/extra-addons/custom-addons
                - /home/backups:/mnt/backups
                - odoo-data:/var/lib/odoo
        networks:
                - tritel_index
   nginx:
        image: nginx:latest
        container_name: index_nginx
        ports:
                - "80:80"
                - "443:443"
        restart: always
        depends_on:
                - odoo
        volumes:
                - ./nginx/sites-enabled/:/etc/nginx/conf.d:ro
                - /etc/letsencrypt:/etc/letsencrypt:ro
        networks:
                - tritel_index
volumes:
        odoo-data:
        db-data:
networks:
         tritel_index:
